### ISSUE TITLE
Shops does not work since update

### ISSUE THREAD

**Issue by crymates** [maxanier/PlayerShops#1]
Hey Max,

since I updated from 1.2 to 1.3 the existing shops do not work anymore.
If you want I check my logs for error logs.

Greetz,
Hannes

**Comment by maxanier** [comment]
But newly created ones work?
This is strange, because I can't remember changing anything that could cause this.

I guess if you click them nothing happens?
Then I need the logs to find the issue

**Comment by crymates** [comment]
Hey max,

I fixed the bug with updating the server to newest spongeforge ;]
It runs perfectly with spongeforge-1.11.2-2201-6.0.0-BETA-2040.

Greetz,
Hannes
